<?php
/**
 * @file
 * Code for the Feature Basic Content feature.
 */

include_once 'feature_basic_content.features.inc';


/**
 *  Implements hook_node_view().
 */
function feature_basic_content_node_view($node, $view_mode, $langcode) {

  switch ($node->type) {
    case 'basic_page':
      if (isset($node->field_basic_page_tabs)) {
        $settings = array(
          'hide_empty_tabs' => TRUE,
          'ajax' => FALSE,
          'style' => 'Zen',
          'default_tab' => 0,
        );
        $tabs = array();
        $content = $node->content;

        if (isset($content['field_basic_page_tabs'])) {
          foreach ($content['field_basic_page_tabs']['#items'] as $delta => $item) {
            $tab = $content['field_basic_page_tabs'][$delta]['entity']['field_collection_item'][$item['value']];
            $tabs[] = array(
              'title' => isset($tab['field_basic_page_tab_label']) ? $tab['field_basic_page_tab_label'][0]['#markup'] : 'Tab',
              'contents' => array(
                '#markup' => isset($tab['field_basic_page_tab_body']) ? $tab['field_basic_page_tab_body'][0]['#markup'] : '',
              ),
            );
          }
          $quicktab = quicktabs_build_quicktabs('content-tab', $settings, $tabs);
          $node->content['field_basic_page_tabs'] = $quicktab;
        }
      }
      break;
  }
}