<?php
/**
 * @file
 * Code for the Feature Basic Site Configuration feature.
 */

include_once 'feature_basic_config.features.inc';

function feature_basic_config_init() {
  drupal_add_css('.media-list-thumbnails .form-type-checkbox {top:0;}', 'inline');
}

function feature_basic_config_preprocess_html(&$vars) {
  //if the user is not an administrator, adds a css file to hide certain settings.
  global $user;
  if (!in_array('administrator', $user->roles)) {
    drupal_add_css('.system-themes-list-disabled, #system-themes-admin-form {display:none; }', "inline");
  }
}