<?php
/**
 * @file
 * Code for the Feature Sliver feature.
 */
include_once 'feature_sliver.features.inc';
/*
 * Implements hook_permissions()
 */
function feature_sliver_permission() {
  return array(
    'admin az sliver' => array(
      'title' => t('Administer Sliver Settings'),
    ),
  );
}

/*
 * Implements hook_menu()
 */
function feature_sliver_menu() {
  $items['admin/config/sliver'] = array(
    'title' => "Sliver Settings",
    'type' => MENU_NORMAL_ITEM,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('feature_sliver_admin_form'),
    'access arguments' => array('admin az sliver'),
  );
  return $items;
}

/*
 * Implements hook_admin_form
 */
function feature_sliver_admin_form() {
  $local = drupal_get_path('module', 'feature_sliver') . '/lib/sliver.js';
  $remote = 'https://static.az.gov/sliver/sliver.js';


  $form = array();
  $form['sliver_js_location'] = array(
    '#type' => 'radios',
    '#title' => t('Location of the Sliver File'),
    '#description' => t('Check this to obtain the remote sliver file.'),
    '#default_value' => variable_get('sliver_js_location', $remote),
    '#options' => array(
      $remote => 'Remote',
      $local => 'Local',
      'off' => 'Disabled'
    ),
  );
  return system_settings_form($form);
}

/*
 * Implements hook_block_info().
 */
function feature_sliver_block_info() {
  $blocks = array();
  $blocks['sliver'] = array(
    'info' => t('Sliver'),
    'cache' => DRUPAL_CACHE_GLOBAL,
  );
  return $blocks;
}

/*
 * Implements hook_block_view().
 */
function feature_sliver_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'sliver':
      $block['subject'] = '';
      $block['content'] = array(
        '#markup' => '',
        '#attached' => array(
          'css' => array(),
          'js' => array(
            array(
              'type' => 'external',
              'data' => feature_sliver_get_library_file(),
              'scope' => 'footer',
            )
          ),
        ),
      );
      if ($block['content']['#attached']['js'][0] == ''){
        unset($block['content']['#attached']['js']);
      }
      break;
  }
  return $block;
}

/**
 * Helper function gets the path to the library Javascript file
 */
function feature_sliver_get_library_file() {
  $path = variable_get('sliver_js_location', 'https://static.az.gov/sliver/sliver.js');
  if ($path == 'off') {
    $path = '';
  }
  return $path;
}